### ISSUE TITLE
Many Issues on raspberry pi 3 model b

### ISSUE THREAD

**Issue by ali77gh** [manjaro-arm/rpi4-images#11]
This issues happend on a Manjaro ARM XFCE 21.10.

Not working:
> network interface not working.
> ip addr command  (not responding)
> ip route command (not responding)
> reboot stuck in manjaro logo and preloader animation.
> firefox and other web browser not opening without error.

Working:
>Terminal
>File manager

**Comment by Strit** [comment]
You should ask for support on our forum: https://forum.manjaro.org/c/arm/technical-assistance/110.

The github issues are for issues building the images.
